# Generated by Django 5.0.2 on 2024-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
