# Generated by Django 5.0.2 on 2024-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_autor_cidade_autor_site_alter_autor_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="email",
        ),
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="editora",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
