# Generated by Django 5.0.2 on 2024-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_autor_cidade_remove_autor_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="site",
        ),
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
